FROM php:7.0
RUN apt-get -qq update && apt-get install -y less mariadb-client apache2

ARG wp_admin_email
ARG wp_admin_pass
ARG wp_admin_user
ARG wp_db_name
ARG wp_db_user
ARG wp_dir
ARG wp_group
ARG wp_title
ARG wp_url
ARG wp_user

RUN groupadd ${wp_group}
RUN useradd -r -u 1001 -g ${wp_group} ${wp_user}

# Download wpcli and move to $PATH
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

# Create wordpress www directory and wordpress user home directory
RUN mkdir -p ${wp_dir}
RUN mkdir -p /home/${wp_user}

# Change ownership of all files in www dir and home dir to wordpress user
RUN chown -R ${wp_user}:${wp_group} ${wp_dir}
RUN chown -R ${wp_user}:${wp_group} /home/${wp_user}

RUN service apache2 start

USER wordpress
RUN wp core download --path=${wp_dir}
